# Generated by Django 4.2.5 on 2023-09-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=8)),
                ('is_vet', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_shelter', models.BooleanField(default=False)),
            ],
        ),
    ]
