# Generated by Django 4.2.5 on 2023-09-05 18:21

from django.db import migrations, models
import tailsup.models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='', max_length=10)),
                ('shelterid', models.CharField(default='', max_length=10, null=True)),
                ('pet_id', models.IntegerField(default='')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vetid', models.CharField(default='', max_length=10)),
                ('userid', models.CharField(default='', max_length=10)),
                ('petid', models.IntegerField(default='')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('medicalid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_id', models.IntegerField(default='')),
                ('userid', models.CharField(default='', max_length=10)),
                ('vetid', models.CharField(max_length=10, null=True)),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(default='', max_length=500)),
                ('report', tailsup.models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='', max_length=10)),
                ('productid', models.IntegerField(default='')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(default='')),
                ('vendor_id', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('stock', models.CharField(default='', max_length=4)),
                ('price', models.CharField(default='', max_length=6)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vetid', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='golden', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='shelterid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='special_needs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='userid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
