# Generated by Django 4.2.5 on 2023-09-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0003_product_amount_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='', max_length=4, null=True),
        ),
    ]
