# Generated by Django 4.2.5 on 2023-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0004_alter_product_amount_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
