# Generated by Django 4.2.5 on 2023-09-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0005_alter_product_amount_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='userid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
