# Generated by Django 4.2.5 on 2023-09-22 00:09

from django.db import migrations
import tailsup.models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0007_alter_pet_shelterid_alter_pet_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=tailsup.models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=tailsup.models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=tailsup.models.FileField(null=True, upload_to=''),
        ),
    ]
