# Generated by Django 4.2.5 on 2023-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0009_user_num_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='userid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
