# Generated by Django 4.2.5 on 2023-09-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0010_alter_pet_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='favourited',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
