# Generated by Django 4.2.5 on 2023-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0011_pet_favourited'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavPets',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='favourited',
        ),
    ]
