# Generated by Django 4.2.5 on 2023-09-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0012_favpets_remove_pet_favourited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavPets',
        ),
    ]
