# Generated by Django 4.2.5 on 2023-09-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0015_alter_favpet_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='isFav',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
