# Generated by Django 4.2.5 on 2023-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0017_alter_pet_isfav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='shelterid',
        ),
        migrations.AddField(
            model_name='adoption',
            name='reason',
            field=models.CharField(default='', max_length=500),
        ),
    ]
