# Generated by Django 4.2.5 on 2023-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0019_adoption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='pet_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
