# Generated by Django 4.2.5 on 2023-09-24 11:45

from django.db import migrations
import tailsup.models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0020_adoption_pet_name_alter_adoption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=tailsup.models.FileField(null=True, upload_to=''),
        ),
    ]
