# Generated by Django 4.2.5 on 2023-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0021_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailsup.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailsup.user')),
            ],
        ),
    ]
