# Generated by Django 4.2.5 on 2023-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0023_availableslot_slot_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
