# Generated by Django 4.2.5 on 2023-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0024_alter_appointments_date_alter_availableslot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='vetname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
