# Generated by Django 4.2.5 on 2023-09-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0025_appointments_vetname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='medicalid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
