# Generated by Django 4.2.5 on 2023-09-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0026_alter_appointments_medicalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='treatment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
