# Generated by Django 4.2.5 on 2023-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0027_medical_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
