# Generated by Django 4.2.5 on 2023-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailsup', '0028_alter_medical_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='apptid',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
